user=myabcuser
password=p@ss-word
host=localhost
myabcdataUrlReal=http://www.canabrewing.com/blocks
myabcdataUrl=http://localhost:8080/myabcdata
fromEmail=mgrantham@canalbrewing.com
smtpServer=njdz3.dailyrazor.com
smtpPort=465
mailAccount=mgrantham@canalbrewing.com
mailPassword=C@tch-two002